### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by centratelemedia** [adinyahya/whatsrice#2]
const { state, saveState } = useSingleFileAuthState(session)
                             ^

TypeError: useSingleFileAuthState is not a function
    at Object.<anonymous> (D:\projects\nodejs\whatsrice\index.js:25:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by adinyahya** [comment]
npm i @adiwajshing/baileys@4.3.0

**Comment by ceceps** [comment]
masih error mas @adinyahya  stlh diupdate muncul message sbb:

```

TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.
    at makeSocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:35:13)
    at makeChatsSocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:19:42)
    at makeGroupsSocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:10:46)
    at makeMessagesSocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:17:48)
    at makeMessagesRecvSocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:15:57)
    at makeBusinessSocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/business.js:9:61)
    at makeWASocket (/home/ceceps/docker/nodejs/whatsrice/node_modules/@adiwajshing/baileys/lib/Socket/index.js:6:69)
    at connectToWhatsApp (/home/ceceps/docker/nodejs/whatsrice/index.js:72:16)
    at Object.<anonymous> (/home/ceceps/docker/nodejs/whatsrice/index.js:162:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
cronjob berjalan
```

dimohon saran untuk perbaikannya
